- hosts: localhost
  tasks:
  
  - name: get pip
    get_url: 
      url: https://bootstrap.pypa.io/get-pip.py
      dest: /tmp/get-pip.py
  
  - name: install pip
    command: /usr/bin/python /tmp/get-pip.py
  
  - name: install awscli
    command: pip install awscli

  - name: Install docker.py
    command: pip install docker.py

     
      