# ansible-playbook playbooks/vscode.playbook.yml --become --ask-become-pass

- hosts: localhost
  tasks:
  - name: Get microsoft apt key
    apt_key: 
      url: https://packages.microsoft.com/keys/microsoft.asc
      keyring: /etc/apt/trusted.gpg.d/microsoft.gpg

  - name: Install repo
    command: sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

  - name: Upgrade all packages to the latest version
    apt:
      update_cache: yes

  - name: Install Visual Studio Code
    apt:
      pkg: "code"
      state: "latest"